---
- name: Configure Desktop
  hosts: localhost
  become: no

  roles:
    - name: apt-system-cli-utilites
    - become: yes
    - name: apt-ppa-jottacloud-cli
    - become: yes
    - name: deb-r-rstudio
    - become: yes
    - name: gui-software
    - become: yes
    - name: ansible-role-vscodium
      become: no
    - name: neuroimaging-software
    - become: yes